// import "./globals.css";
import "../../assets/css/plugins/fontawesome-6.css";
import "../../assets/css/plugins/sal.min.css";
import "../../assets/css/plugins/magnific-popup.css";
import "../../assets/css/vendor/bootstrap.min.css";
import "../../assets/css/plugins.min.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/scrollbar';
import 'swiper/swiper-bundle.css';
import "../../assets/css/style.css";
import 'sal.js/dist/sal.css';
import 'react-modal-video/css/modal-video.min.css';


export const metadata = {
  title: "Hostie - Web Hosting & WHMCS NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/fav.png", // Ensure the path is correct
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={metadata.icons.icon} />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body>{children}</body>
    </html>
  );
}